version: "3.8"
services:
  rs-scraper-mongodb:
    image: mongo:4.4-focal
    container_name: rs-scraper-mongodb
    restart: always
    expose:
      - "27017"
    ports:
      - 27017:27017
    volumes:
      - rs-scraper-mongodb:/rs-scraper-mongodb/databaseVolume
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
  mongo-express:
    image: mongo-express
    container_name: rs-scraper-mongo-express
    depends_on:
      - rs-scraper-mongodb
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: rs-scraper-mongodb
  rs-scraper-api:
    build:
      context: ./rs-scraper-api/
    image: peterkollerlv/rs-scraper-api
    container_name: rs-scraper-api
    depends_on:
      - rs-scraper-mongodb
    restart: always
    expose:
      - "4242"
    ports:
      - "${API_PORT}:4242"
    environment:
      - NODE_ENV=${API_NODE_ENV}
      - HELLO=${HELLO}
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - MONGO_SERVER=${MONGO_SERVER}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_ENV=${MONGO_ENV}
      - MONGO_USR=${MONGO_USR}
      - MONGO_SECRET=${MONGO_SECRET}
      - MONGO_DB=${MONGO_DB}
  rs-scraper-ui:
    build:
      context: ./rs-scraper-ui/
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    image: peterkollerlv/rs-scraper-ui
    container_name: rs-scraper-ui
    restart: always
    expose:
      - "3000"
    ports:
      - ${UI_PORT}:3000
    environment:
      - NODE_ENV=${UI_NODE_ENV}
volumes:
  rs-scraper-mongodb:
