version: "3.8"
services:
  rs-scraper-mongodb:
    image: mongo:4.4-focal
    container_name: rs-scraper-mongodb
    restart: always
    volumes:
      - rs-scraper-mongodb:/rs-scraper-mongodb/databaseVolume
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rs-scraper

  mongo-express:
    image: mongo-express
    container_name: rs-scraper-mongodb-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rs-scraper
  rs-scraper-api:
    build:
      context: ./rs-scraper-api/
    image: peterkollerlv/rs-scraper-api
    container_name: rs-scraper-api
    restart: always
    expose:
      - "4242"
    ports:
      - "4242:4242"
  rs-scraper-ui:
    build:
      context: ./rs-scraper-ui/
    image: peterkollerlv/rs-scraper-ui
    container_name: rs-scraper-ui
    restart: always
    expose:
      - "3000"
    ports:
      - 3000:3000
volumes:
  rs-scraper-mongodb:
